name: Test

on: [push, pull_request]
jobs:
  UnitTests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100-preview.8.20417.9'
    - name: Test
      run: |
        dotnet add "UnitTests" package Microsoft.NET.Test.Sdk
        dotnet add "UnitTests" package GitHubActionsTestLogger
        dotnet add "UnitTests" package coverlet.msbuild
        dotnet test "UnitTests" -c Release -l GitHubActions /p:CollectCoverage=true
    - uses: codecov/codecov-action@v1
      with:
        file: .UnitTests/coverage.json
        flags: unittests
        name: codecov-umbrella
      run: |
        curl -s https://codecov.io/bash